### PR TITLE
perf: change import path

### PR DESCRIPTION
**Pull request by ZLY201**
## What is the current behavior?

Change the import path of js-sdsl.

## What is the new behavior?

No new behavior.

## Why did you make this change?

Hey, I'm the developer of js-sdsl. I'm so glad that you use it. But I see you use the absolute path to import the member. I think this is not a good behavior so I submitted this PR.

The export path may be changed in the future.

### Checklist

- [x] I'm not PR to the master branch.
- [x] Commit message was checked by commitlint.

### CODE REVIEW

**Review by noname0310 — CHANGES_REQUESTED** [review]
Test failed at test/test_project/asset/script/Spawner.ts.

The error contents are as follows:
```
FAIL test/GameCreate.test.ts
  ● Test suite failed to run

    test/test_project/asset/script/Spawner.ts:26:25 - error TS2339: Property 'push' does not exist on type 'Deque<GameObject>'.

    26             this._queue.push(this.gameObject.addChildFromBuilder(
                               ~~~~
    test/test_project/asset/script/Spawner.ts:33:33 - error TS2339: Property 'pop' does not exist on type 'Deque<GameObject>'.

    33                     this._queue.pop();
                                       ~~~
    test/test_project/asset/script/Spawner.ts:38:33 - error TS2339: Property 'pop' does not exist on type 'Deque<GameObject>'.

    38                     this._queue.pop();
                                       ~~~
    test/test_project/asset/script/Spawner.ts:47:25 - error TS2339: Property 'push' does not exist on type 'Deque<GameObject>'.

    47             this._queue.push(this.gameObject.addChildFromBuilder(
                               ~~~~
```

Please solve this problem

**Comment by ZLY201** [comment]
> Test failed at test/test_project/asset/script/Spawner.ts.
> 
> The error contents are as follows:
> 
> ```
> FAIL test/GameCreate.test.ts
>   ● Test suite failed to run
> 
>     test/test_project/asset/script/Spawner.ts:26:25 - error TS2339: Property 'push' does not exist on type 'Deque<GameObject>'.
> 
>     26             this._queue.push(this.gameObject.addChildFromBuilder(
>                                ~~~~
>     test/test_project/asset/script/Spawner.ts:33:33 - error TS2339: Property 'pop' does not exist on type 'Deque<GameObject>'.
> 
>     33                     this._queue.pop();
>                                        ~~~
>     test/test_project/asset/script/Spawner.ts:38:33 - error TS2339: Property 'pop' does not exist on type 'Deque<GameObject>'.
> 
>     38                     this._queue.pop();
>                                        ~~~
>     test/test_project/asset/script/Spawner.ts:47:25 - error TS2339: Property 'push' does not exist on type 'Deque<GameObject>'.
> 
>     47             this._queue.push(this.gameObject.addChildFromBuilder(
>                                ~~~~
> ```
> 
> Please solve this problem

Sorry, I used wrong queue type.

**Review by noname0310 — APPROVED** [review]
It's confirmed. Thank you.

**Comment by noname0310** [comment]
@all-contributors please add @ZLY201 for code

**Comment by noname0310** [comment]
I just checked the difference in the import method.

Import in `import { foo } from "js-sdsl"` will not become tree-shaking and all unused references are added to bundle.

In order to reduce bundle size, import by specifying a particular path

Here is the difference between `import { foo } from "js-sdsl"` and `import foo from "js-sdsl/dist/esm/container/foo";`

`import { foo } from "js-sdsl"`| "js-sdsl/dist/esm/container/foo";`
---|---
|

I don't know why, but from a tree-shaking point of view, it's not a good idea to import in the `import { foo } from "js-sdsl"` way.

**Comment by ZLY201** [comment]
> @ZLY201 I just checked the difference in the import method.
> 
> Import in `import { foo } from "js-sdsl"` will not become tree-shaking and all unused references are added to bundle.
> 
> In order to reduce bundle size, import by specifying a particular path
> 
> Here is the difference between `import { foo } from "js-sdsl"` and `import foo from "js-sdsl/dist/esm/container/foo";`
> 
> `import { foo } from "js-sdsl"`: 136.26KB	`"js-sdsl/dist/esm/container/foo";`: 61.04KB
> 	
> I don't know why, but from a tree-shaking point of view, it's not a good idea to import in the `import { foo } from "js-sdsl"` way.

I don't know why webpack tree shaking is not work in js-sdsl. But explicitly setting its side effect to false will succeed.

Next, I will investigate the cause and hope to fix it in subsequent versions.

Thanks to tell me about that. :)

See [here](https://github.com/The-World-Space/the-world-engine.ts/pull/55).

**Pull request merged**
